[workspace]
resolver = "2"
members = [
    "core/idphoto",
    "bindings/wasm",
    "bindings/python",
    "bindings/jni",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jeremi/idphoto"
